export type PassportCountry = { code: string; en: string; cn: string };

export const PASSPORT_COUNTRIES: PassportCountry[] = [
  { code: "CHN", en: "China", cn: "中国" },
  { code: "HKG", en: "Hong Kong", cn: "中国香港" },
  { code: "MAC", en: "Macao", cn: "中国澳门" },
  { code: "TWN", en: "Taiwan", cn: "台湾" },
  { code: "AFG", en: "Afghanistan", cn: "阿富汗" },
  { code: "ALB", en: "Albania", cn: "阿尔巴尼亚" },
  { code: "DZA", en: "Algeria", cn: "阿尔及利亚" },
  { code: "AND", en: "Andorra", cn: "安道尔" },
  { code: "AGO", en: "Angola", cn: "安哥拉" },
  { code: "ATG", en: "Antigua and Barbuda", cn: "安提瓜和巴布达" },
  { code: "ARG", en: "Argentina", cn: "阿根廷" },
  { code: "ARM", en: "Armenia", cn: "亚美尼亚" },
  { code: "AUS", en: "Australia", cn: "澳大利亚" },
  { code: "AUT", en: "Austria", cn: "奥地利" },
  { code: "AZE", en: "Azerbaijan", cn: "阿塞拜疆" },
  { code: "BHS", en: "Bahamas", cn: "巴哈马" },
  { code: "BHR", en: "Bahrain", cn: "巴林" },
  { code: "BGD", en: "Bangladesh", cn: "孟加拉国" },
  { code: "BRB", en: "Barbados", cn: "巴巴多斯" },
  { code: "BLR", en: "Belarus", cn: "白俄罗斯" },
  { code: "BEL", en: "Belgium", cn: "比利时" },
  { code: "BLZ", en: "Belize", cn: "伯利兹" },
  { code: "BEN", en: "Benin", cn: "贝宁" },
  { code: "BTN", en: "Bhutan", cn: "不丹" },
  { code: "BOL", en: "Bolivia", cn: "玻利维亚" },
  { code: "BIH", en: "Bosnia and Herzegovina", cn: "波斯尼亚和黑塞哥维那" },
  { code: "BWA", en: "Botswana", cn: "博茨瓦纳" },
  { code: "BRA", en: "Brazil", cn: "巴西" },
  { code: "BRN", en: "Brunei", cn: "文莱" },
  { code: "BGR", en: "Bulgaria", cn: "保加利亚" },
  { code: "BFA", en: "Burkina Faso", cn: "布基纳法索" },
  { code: "BDI", en: "Burundi", cn: "布隆迪" },
  { code: "CPV", en: "Cabo Verde", cn: "佛得角" },
  { code: "KHM", en: "Cambodia", cn: "柬埔寨" },
  { code: "CMR", en: "Cameroon", cn: "喀麦隆" },
  { code: "CAN", en: "Canada", cn: "加拿大" },
  { code: "CAF", en: "Central African Republic", cn: "中非" },
  { code: "TCD", en: "Chad", cn: "乍得" },
  { code: "CHL", en: "Chile", cn: "智利" },
  { code: "COL", en: "Colombia", cn: "哥伦比亚" },
  { code: "COM", en: "Comoros", cn: "科摩罗" },
  { code: "COG", en: "Congo", cn: "刚果（布）" },
  { code: "COD", en: "Congo (DRC)", cn: "刚果（金）" },
  { code: "CRI", en: "Costa Rica", cn: "哥斯达黎加" },
  { code: "CIV", en: "Cote d'Ivoire", cn: "科特迪瓦" },
  { code: "HRV", en: "Croatia", cn: "克罗地亚" },
  { code: "CUB", en: "Cuba", cn: "古巴" },
  { code: "CYP", en: "Cyprus", cn: "塞浦路斯" },
  { code: "CZE", en: "Czechia", cn: "捷克" },
  { code: "DNK", en: "Denmark", cn: "丹麦" },
  { code: "DJI", en: "Djibouti", cn: "吉布提" },
  { code: "DMA", en: "Dominica", cn: "多米尼克" },
  { code: "DOM", en: "Dominican Republic", cn: "多米尼加" },
  { code: "ECU", en: "Ecuador", cn: "厄瓜多尔" },
  { code: "EGY", en: "Egypt", cn: "埃及" },
  { code: "SLV", en: "El Salvador", cn: "萨尔瓦多" },
  { code: "GNQ", en: "Equatorial Guinea", cn: "赤道几内亚" },
  { code: "ERI", en: "Eritrea", cn: "厄立特里亚" },
  { code: "EST", en: "Estonia", cn: "爱沙尼亚" },
  { code: "SWZ", en: "Eswatini", cn: "斯威士兰" },
  { code: "ETH", en: "Ethiopia", cn: "埃塞俄比亚" },
  { code: "FJI", en: "Fiji", cn: "斐济" },
  { code: "FIN", en: "Finland", cn: "芬兰" },
  { code: "FRA", en: "France", cn: "法国" },
  { code: "GAB", en: "Gabon", cn: "加蓬" },
  { code: "GMB", en: "Gambia", cn: "冈比亚" },
  { code: "GEO", en: "Georgia", cn: "格鲁吉亚" },
  { code: "DEU", en: "Germany", cn: "德国" },
  { code: "GHA", en: "Ghana", cn: "加纳" },
  { code: "GRC", en: "Greece", cn: "希腊" },
  { code: "GRD", en: "Grenada", cn: "格林纳达" },
  { code: "GTM", en: "Guatemala", cn: "危地马拉" },
  { code: "GIN", en: "Guinea", cn: "几内亚" },
  { code: "GNB", en: "Guinea-Bissau", cn: "几内亚比绍" },
  { code: "GUY", en: "Guyana", cn: "圭亚那" },
  { code: "HTI", en: "Haiti", cn: "海地" },
  { code: "HND", en: "Honduras", cn: "洪都拉斯" },
  { code: "HUN", en: "Hungary", cn: "匈牙利" },
  { code: "ISL", en: "Iceland", cn: "冰岛" },
  { code: "IND", en: "India", cn: "印度" },
  { code: "IDN", en: "Indonesia", cn: "印度尼西亚" },
  { code: "IRN", en: "Iran", cn: "伊朗" },
  { code: "IRQ", en: "Iraq", cn: "伊拉克" },
  { code: "IRL", en: "Ireland", cn: "爱尔兰" },
  { code: "ISR", en: "Israel", cn: "以色列" },
  { code: "ITA", en: "Italy", cn: "意大利" },
  { code: "JAM", en: "Jamaica", cn: "牙买加" },
  { code: "JPN", en: "Japan", cn: "日本" },
  { code: "JOR", en: "Jordan", cn: "约旦" },
  { code: "KAZ", en: "Kazakhstan", cn: "哈萨克斯坦" },
  { code: "KEN", en: "Kenya", cn: "肯尼亚" },
  { code: "KIR", en: "Kiribati", cn: "基里巴斯" },
  { code: "PRK", en: "North Korea", cn: "朝鲜" },
  { code: "KOR", en: "South Korea", cn: "韩国" },
  { code: "KWT", en: "Kuwait", cn: "科威特" },
  { code: "KGZ", en: "Kyrgyzstan", cn: "吉尔吉斯斯坦" },
  { code: "LAO", en: "Laos", cn: "老挝" },
  { code: "LVA", en: "Latvia", cn: "拉脱维亚" },
  { code: "LBN", en: "Lebanon", cn: "黎巴嫩" },
  { code: "LSO", en: "Lesotho", cn: "莱索托" },
  { code: "LBR", en: "Liberia", cn: "利比里亚" },
  { code: "LBY", en: "Libya", cn: "利比亚" },
  { code: "LIE", en: "Liechtenstein", cn: "列支敦士登" },
  { code: "LTU", en: "Lithuania", cn: "立陶宛" },
  { code: "LUX", en: "Luxembourg", cn: "卢森堡" },
  { code: "MDG", en: "Madagascar", cn: "马达加斯加" },
  { code: "MWI", en: "Malawi", cn: "马拉维" },
  { code: "MYS", en: "Malaysia", cn: "马来西亚" },
  { code: "MDV", en: "Maldives", cn: "马尔代夫" },
  { code: "MLI", en: "Mali", cn: "马里" },
  { code: "MLT", en: "Malta", cn: "马耳他" },
  { code: "MHL", en: "Marshall Islands", cn: "马绍尔群岛" },
  { code: "MRT", en: "Mauritania", cn: "毛里塔尼亚" },
  { code: "MUS", en: "Mauritius", cn: "毛里求斯" },
  { code: "MEX", en: "Mexico", cn: "墨西哥" },
  { code: "FSM", en: "Micronesia", cn: "密克罗尼西亚" },
  { code: "MDA", en: "Moldova", cn: "摩尔多瓦" },
  { code: "MCO", en: "Monaco", cn: "摩纳哥" },
  { code: "MNG", en: "Mongolia", cn: "蒙古" },
  { code: "MNE", en: "Montenegro", cn: "黑山" },
  { code: "MAR", en: "Morocco", cn: "摩洛哥" },
  { code: "MOZ", en: "Mozambique", cn: "莫桑比克" },
  { code: "MMR", en: "Myanmar", cn: "缅甸" },
  { code: "NAM", en: "Namibia", cn: "纳米比亚" },
  { code: "NRU", en: "Nauru", cn: "瑙鲁" },
  { code: "NPL", en: "Nepal", cn: "尼泊尔" },
  { code: "NLD", en: "Netherlands", cn: "荷兰" },
  { code: "NZL", en: "New Zealand", cn: "新西兰" },
  { code: "NIC", en: "Nicaragua", cn: "尼加拉瓜" },
  { code: "NER", en: "Niger", cn: "尼日尔" },
  { code: "NGA", en: "Nigeria", cn: "尼日利亚" },
  { code: "MKD", en: "North Macedonia", cn: "北马其顿" },
  { code: "NOR", en: "Norway", cn: "挪威" },
  { code: "OMN", en: "Oman", cn: "阿曼" },
  { code: "PAK", en: "Pakistan", cn: "巴基斯坦" },
  { code: "PLW", en: "Palau", cn: "帕劳" },
  { code: "PAN", en: "Panama", cn: "巴拿马" },
  { code: "PNG", en: "Papua New Guinea", cn: "巴布亚新几内亚" },
  { code: "PRY", en: "Paraguay", cn: "巴拉圭" },
  { code: "PER", en: "Peru", cn: "秘鲁" },
  { code: "PHL", en: "Philippines", cn: "菲律宾" },
  { code: "POL", en: "Poland", cn: "波兰" },
  { code: "PRT", en: "Portugal", cn: "葡萄牙" },
  { code: "QAT", en: "Qatar", cn: "卡塔尔" },
  { code: "ROU", en: "Romania", cn: "罗马尼亚" },
  { code: "RUS", en: "Russia", cn: "俄罗斯" },
  { code: "RWA", en: "Rwanda", cn: "卢旺达" },
  { code: "KNA", en: "Saint Kitts and Nevis", cn: "圣基茨和尼维斯" },
  { code: "LCA", en: "Saint Lucia", cn: "圣卢西亚" },
  { code: "VCT", en: "Saint Vincent and the Grenadines", cn: "圣文森特和格林纳丁斯" },
  { code: "WSM", en: "Samoa", cn: "萨摩亚" },
  { code: "SMR", en: "San Marino", cn: "圣马力诺" },
  { code: "STP", en: "Sao Tome and Principe", cn: "圣多美和普林西比" },
  { code: "SAU", en: "Saudi Arabia", cn: "沙特阿拉伯" },
  { code: "SEN", en: "Senegal", cn: "塞内加尔" },
  { code: "SRB", en: "Serbia", cn: "塞尔维亚" },
  { code: "SYC", en: "Seychelles", cn: "塞舌尔" },
  { code: "SLE", en: "Sierra Leone", cn: "塞拉利昂" },
  { code: "SGP", en: "Singapore", cn: "新加坡" },
  { code: "SVK", en: "Slovakia", cn: "斯洛伐克" },
  { code: "SVN", en: "Slovenia", cn: "斯洛文尼亚" },
  { code: "SLB", en: "Solomon Islands", cn: "所罗门群岛" },
  { code: "SOM", en: "Somalia", cn: "索马里" },
  { code: "ZAF", en: "South Africa", cn: "南非" },
  { code: "SSD", en: "South Sudan", cn: "南苏丹" },
  { code: "ESP", en: "Spain", cn: "西班牙" },
  { code: "LKA", en: "Sri Lanka", cn: "斯里兰卡" },
  { code: "SDN", en: "Sudan", cn: "苏丹" },
  { code: "SUR", en: "Suriname", cn: "苏里南" },
  { code: "SWE", en: "Sweden", cn: "瑞典" },
  { code: "CHE", en: "Switzerland", cn: "瑞士" },
  { code: "SYR", en: "Syria", cn: "叙利亚" },
  { code: "TJK", en: "Tajikistan", cn: "塔吉克斯坦" },
  { code: "TZA", en: "Tanzania", cn: "坦桑尼亚" },
  { code: "THA", en: "Thailand", cn: "泰国" },
  { code: "TLS", en: "Timor-Leste", cn: "东帝汶" },
  { code: "TGO", en: "Togo", cn: "多哥" },
  { code: "TON", en: "Tonga", cn: "汤加" },
  { code: "TTO", en: "Trinidad and Tobago", cn: "特立尼达和多巴哥" },
  { code: "TUN", en: "Tunisia", cn: "突尼斯" },
  { code: "TUR", en: "Turkiye", cn: "土耳其" },
  { code: "TKM", en: "Turkmenistan", cn: "土库曼斯坦" },
  { code: "TUV", en: "Tuvalu", cn: "图瓦卢" },
  { code: "UGA", en: "Uganda", cn: "乌干达" },
  { code: "UKR", en: "Ukraine", cn: "乌克兰" },
  { code: "ARE", en: "United Arab Emirates", cn: "阿联酋" },
  { code: "GBR", en: "United Kingdom", cn: "英国" },
  { code: "USA", en: "United States", cn: "美国" },
  { code: "URY", en: "Uruguay", cn: "乌拉圭" },
  { code: "UZB", en: "Uzbekistan", cn: "乌兹别克斯坦" },
  { code: "VUT", en: "Vanuatu", cn: "瓦努阿图" },
  { code: "VAT", en: "Vatican City", cn: "梵蒂冈" },
  { code: "VEN", en: "Venezuela", cn: "委内瑞拉" },
  { code: "VNM", en: "Vietnam", cn: "越南" },
  { code: "YEM", en: "Yemen", cn: "也门" },
  { code: "ZMB", en: "Zambia", cn: "赞比亚" },
  { code: "ZWE", en: "Zimbabwe", cn: "津巴布韦" },
];

export function countryLabel(c: PassportCountry): string {
  return `${c.cn} ${c.en}`;
}

